### ISSUE TITLE
Orchard connection string

### ISSUE THREAD

**Issue by mausch** [StatCan/charts#14]
Hi and thanks for these charts!

I see the Orchard chart defines Postgres connection details in environment variables in https://github.com/StatCan/charts/blob/master/stable/orchard-cms/templates/_helpers.tpl#L50-L64

However Orchard itself doesn't seem to support reading connection strings from environment variables? i.e. when starting up with an empty app_data it shows the setup page and asks for a connection string...
I looked for GetEnvironmentVariable in the original repo and in https://github.com/StatCan/StatCan.OrchardCore and couldn't find anything relevant... am I missing something?

Again many thanks.

**Comment by justbert** [comment]
Can you respond to this @jptissot?

**Comment by jptissot** [comment]
@mausch I plan on changing this in a future version but for now, the way I am handling this is by using a shell script to start the application that maps the PGSQL variables to the OC Environment variables.

See https://github.com/StatCan/StatCan.OrchardCore/blob/master/src/StatCan.OrchardCore.Cms.Web/docker_run.sh and https://github.com/StatCan/StatCan.OrchardCore/blob/master/src/StatCan.OrchardCore.Cms.Web/Dockerfile#L9

**Comment by jptissot** [comment]
@mausch In the latest version, I removed this mapping and now you have to manually specify the connection string using Orchard environment variables.

```yaml
environmentVariables:
  ASPNETCORE_ENVIRONMENT: production
  OrchardCore__DatabaseProvider: "Postgres"

environmentSecrets:
  OrchardCore__ConnectionString: "User ID=#{POSTGRESQL_USER};Password=#{POSTGRESQL_PASSWORD};Host=#{POSTGRESQL_HOST};Port=5432;Database=#{POSTGRESQL_DATABASE};"
  
```
